INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('101-001','Cash On Hand IDR','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-002','Cash On Hand USD','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-003','Cash On Hand Bdr','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-004','Cash On Hand Mkr','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-005','Cash On Hand Opr','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-006','Cash On Hand Obd','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-007','Cash On Hand Owm','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-008','Cash Tax Amnesty','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-101','Petty Cash Office','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-102','Petty Cash Warehouse','D','BS',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('101-103','Petty Cash Ga','D','BS',NULL,0,'active',NULL,NULL),
	 ('101-109','Inter Cash','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-001','BCA 069 - 3778899','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-002','BCA 069 - 3151888','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-003','BCA 069 - 3589999','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-004','Panin 062-5000-227','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-005','PANIN 115 - 6000727 ( USD )','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-006','BNI  071-017-83006','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-007','MANDIRI  168 - 0037788005 ( USD )','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-008','BCA 069 - 5511189','D','BS',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('102-009','PANIN  115 - 5857888','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-010','BCA 069 - 1199907','D','BS',NULL,0,'active',NULL,NULL),
	 ('102-011','Mandiri 168-0002954038','D','BS',NULL,0,'active',NULL,NULL),
	 ('103-001','Deposit In Bank','D','BS',NULL,0,'active',NULL,NULL),
	 ('104-001','Trade Receivable','D','BS',NULL,0,'active',NULL,NULL),
	 ('106-001','Employee Receivable','D','BS',NULL,0,'active',NULL,NULL),
	 ('106-002','Shareholder Receivable','D','BS',NULL,0,'active',NULL,NULL),
	 ('106-003','Other Receivable','D','BS',NULL,0,'active',NULL,NULL),
	 ('106-004','Debit Note Reiceivable','D','BS',NULL,0,'active',NULL,NULL),
	 ('107-001','Agent D/P','D','BS',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('107-002','Reimbursement Receivable','D','BS',NULL,0,'active',NULL,NULL),
	 ('108-001','Prepaid Pph 23','D','BS',NULL,0,'active',NULL,NULL),
	 ('108-002','Prepaid Pph 4(2)','D','BS',NULL,0,'active',NULL,NULL),
	 ('108-007','Prepaid Pph 25','D','BS',NULL,0,'active',NULL,NULL),
	 ('108-008','Vat In','D','BS',NULL,0,'active',NULL,NULL),
	 ('109-001','Rental Deposit','D','BS',NULL,0,'active',NULL,NULL),
	 ('109-002','Guarantee Deposit','D','BS',NULL,0,'active',NULL,NULL),
	 ('109-003','Container Deposit','D','BS',NULL,0,'active',NULL,NULL),
	 ('109-101','Prepaid Rent','D','BS',NULL,0,'active',NULL,NULL),
	 ('109-102','Prepaid Insurance','D','BS',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('109-103','Prepaid Others','D','BS',NULL,0,'active',NULL,NULL),
	 ('110-001','Land','D','BS',NULL,0,'active',NULL,NULL),
	 ('110-002','Building','D','BS',NULL,0,'active',NULL,NULL),
	 ('110-003','Vehicle','D','BS',NULL,0,'active',NULL,NULL),
	 ('110-004','Office Equipment','D','BS',NULL,0,'active',NULL,NULL),
	 ('110-005','Warehouse Equipment','D','BS',NULL,0,'active',NULL,NULL),
	 ('110-006','Furniture & Fixture','D','BS',NULL,0,'active',NULL,NULL),
	 ('110-008','Software','D','BS',NULL,0,'active',NULL,NULL),
	 ('111-002','Accum. Building Depr','C','BS',NULL,0,'active',NULL,NULL),
	 ('111-003','Accum. Vehicle Depr','C','BS',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('111-004','Accum. Office Equip Depr','C','BS',NULL,0,'active',NULL,NULL),
	 ('111-005','Accum. Warehouse Equip Depr','C','BS',NULL,0,'active',NULL,NULL),
	 ('111-006','Accum. Furn & Fixture Depr','C','BS',NULL,0,'active',NULL,NULL),
	 ('111-008','Accum. Software Amort','C','BS',NULL,0,'active',NULL,NULL),
	 ('180-001','Investment In Stocks','D','BS',NULL,0,'active',NULL,NULL),
	 ('201-001','Trade Payable','C','BS',NULL,0,'active',NULL,NULL),
	 ('202-001','Financing Payable - Short Term','C','BS',NULL,0,'active',NULL,NULL),
	 ('202-003','Bank Loan - Short Term','C','BS',NULL,0,'active',NULL,NULL),
	 ('202-008','Shareholder Loan - Short Term','C','BS',NULL,0,'active',NULL,NULL),
	 ('202-009','Other Payable','C','BS',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('203-001','Pph 21 Payable','C','BS',NULL,0,'active',NULL,NULL),
	 ('203-002','Pph 23 Payable','C','BS',NULL,0,'active',NULL,NULL),
	 ('203-003','Pph 4(2) Payable','C','BS',NULL,0,'active',NULL,NULL),
	 ('203-006','Pph 25 Payable','C','BS',NULL,0,'active',NULL,NULL),
	 ('203-007','Pph 29 Payable','C','BS',NULL,0,'active',NULL,NULL),
	 ('203-008','Vat Out','C','BS',NULL,0,'active',NULL,NULL),
	 ('203-009','Vat Payable','C','BS',NULL,0,'active',NULL,NULL),
	 ('204-001','Customer Down Payment','C','BS',NULL,0,'active',NULL,NULL),
	 ('204-002','Refundable Cust.Deposit','C','BS',NULL,0,'active',NULL,NULL),
	 ('205-001','Accrued Cost','C','BS',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('205-002','Accrued Expenses','C','BS',NULL,0,'active',NULL,NULL),
	 ('205-003','Suspense Account','C','BS',NULL,0,'active',NULL,NULL),
	 ('211-001','Financing Payable - Lt','C','BS',NULL,0,'active',NULL,NULL),
	 ('211-003','Bank Loan - Lt','C','BS',NULL,0,'active',NULL,NULL),
	 ('211-008','Shareholder Loan - Lt','C','BS',NULL,0,'active',NULL,NULL),
	 ('310-001','Paid In Capital','C','BS',NULL,0,'active',NULL,NULL),
	 ('311-001','Retained Earnings','C','BS',NULL,0,'active',NULL,NULL),
	 ('311-002','Dividend','D','BS',NULL,0,'active',NULL,NULL),
	 ('311-008','Current Year Earnings','C','BS',NULL,0,'active',NULL,NULL),
	 ('411-000','Sales Warehouse','C','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('411-101','Sales Warehouse Tps  Umum - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('411-111','Sales Warehouse Tps  Umum - Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('411-201','Sales Warehouse  Pjt - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('411-211','Sales Warehouse  Pjt - Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-000','Sales Handling','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-101','Sales Handling Import - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-109','Sales Handling Import - Air All In','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-111','Sales Handling Import - Sea Fcl 20','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-112','Sales Handling Import - Sea Fcl 40','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-113','Sales Handling Import - Sea Fcl 45','C','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('421-115','Sales Handling Import - Sea Lcl','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-116','Sales Handling Import - Sea General','D','PL',NULL,0,'active',NULL,NULL),
	 ('421-119','Sales Handling Import - Sea All In','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-201','Sales Handling Export - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-209','Sales Handling Export - Air All In','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-211','Sales Handling Export - Sea Fcl 20','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-212','Sales Handling Export - Sea Fcl 40','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-213','Sales Handling Export - Sea Fcl 45','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-215','Sales Handling Export - Sea Lcl','C','PL',NULL,0,'active',NULL,NULL),
	 ('421-219','Sales Handling Export - Sea All In','C','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('422-000','Sales Freight','C','PL',NULL,0,'active',NULL,NULL),
	 ('422-101','Sales Freight Import - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('422-111','Sales Freight Import - Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('422-201','Sales Freight Export - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('422-211','Sales Freight Export - Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('423-000','Sales Document Fee','C','PL',NULL,0,'active',NULL,NULL),
	 ('423-101','Sales Doc. Fee Import - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('423-111','Sales Doc. Fee Import - Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('423-201','Sales Doc. Fee Export - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('423-211','Sales Doc. Fee Export - Sea','C','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('425-000','Sales Trucking','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-101','Sales Trucking Sc Import - Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-108','Sales Trucking Import - Air Gen. Charge','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-111','Sales Trucking Sc Import - Sea Fcl 20','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-112','Sales Trucking Sc Import - Sea Fcl 40','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-113','Sales Trucking Sc Import - Sea Fcl 45','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-115','Sales Trucking Sc Import - Sea Lcl','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-116','Sales Trucking Import - Sea Truck','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-118','Sales Trucking Import - Sea Gen. Charge','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-201','Sales Trucking Sc Export - Air','C','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('425-208','Sales Trucking Export - Air Gen. Charge','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-211','Sales Trucking Sc Export - Sea Fcl 20','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-212','Sales Trucking Sc Export - Sea Fcl 40','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-213','Sales Trucking Sc Export - Sea Fcl 45','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-215','Sales Trucking Sc Export - Sea Lcl','C','PL',NULL,0,'active',NULL,NULL),
	 ('425-218','Sales Trucking Export - Sea Gen. Charge','C','PL',NULL,0,'active',NULL,NULL),
	 ('426-000','Sales Logistic','C','PL',NULL,0,'active',NULL,NULL),
	 ('426-101','Sales Fullfilment','C','PL',NULL,0,'active',NULL,NULL),
	 ('426-102','Sales Rental Logistic','C','PL',NULL,0,'active',NULL,NULL),
	 ('426-103','Sales Contract Logistic','C','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('426-104','Sales Trucking Logistic','C','PL',NULL,0,'active',NULL,NULL),
	 ('427-000','Sales Transfer Edi','C','PL',NULL,0,'active',NULL,NULL),
	 ('427-101','Sales Transfer Edi Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('427-111','Sales Transfer Edi Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('428-000','Sales Insurance','C','PL',NULL,0,'active',NULL,NULL),
	 ('428-101','Sales Insurance Import Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('428-111','Sales Insurance Import Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('428-201','Sales Insurance Export Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('428-211','Sales Insurance Export Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('429-101','Sales Other Import Air','C','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('429-111','Sales Other Import Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('429-201','Sales Other Export Air','C','PL',NULL,0,'active',NULL,NULL),
	 ('429-211','Sales Other Export Sea','C','PL',NULL,0,'active',NULL,NULL),
	 ('511','Cost Of Warehouse','D','PL',NULL,0,'active',NULL,NULL),
	 ('511-000','Cost Of Warehouse','D','PL',NULL,0,'active',NULL,NULL),
	 ('511-101','Cost Of Warehouse Tps Umum - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('511-111','Cost Of Warehouse Tps Umum - Sea','D','PL',NULL,0,'active',NULL,NULL),
	 ('511-201','Cost Of Warehouse Pjt - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('511-211','Cost Of Warehouse Pjt - Sea','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-000','Cost Of Handling','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('521-101','Cost Of Handling Import - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-109','Cost Of Handling Import - Air All In','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-111','Cost Of Handling Import - Sea Fcl 20','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-112','Cost Of Handling Import - Sea Fcl 40','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-113','Cost Of Handling Import - Sea Fcl 45','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-115','Cost Of Handling Import - Sea Lcl','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-116','Cost Of Handling Import - Sea General','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-119','Cost Of Handling Import - Sea All In','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-201','Cost Of Handling Export - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-209','Cost Of Handling Export - Air All In','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('521-211','Cost Of Handling Export - Sea Fcl 20','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-212','Cost Of Handling Export - Sea Fcl 40','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-213','Cost Of Handling Export - Sea Fcl 45','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-215','Cost Of Handling Export - Sea Lcl','D','PL',NULL,0,'active',NULL,NULL),
	 ('521-219','Cost Of Handling Export - Sea All In','D','PL',NULL,0,'active',NULL,NULL),
	 ('522-000','Cost Of Freight','D','PL',NULL,0,'active',NULL,NULL),
	 ('522-101','Cost Of Freight Import - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('522-111','Cost Of Freight Import - Sea','D','PL',NULL,0,'active',NULL,NULL),
	 ('522-201','Cost Of Freight Export - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('522-211','Cost Of Freight Export - Sea','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('523-000','Cost Of Document Fee','D','PL',NULL,0,'active',NULL,NULL),
	 ('523-101','Cost Of Doc. Fee Import - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('523-111','Cost Of Doc. Fee Import - Sea','D','PL',NULL,0,'active',NULL,NULL),
	 ('523-201','Cost Of Doc. Fee Export - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('523-211','Cost Of Doc. Fee Export - Sea','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-000','Cost Of Trucking','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-101','Cost Of Trucking Sc Import - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-108','Cost Of Trucking Import - Air Gen. Charge','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-111','Cost Of Trucking Sc Import - Sea Fcl 20','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-112','Cost Of Trucking Sc Import - Sea Fcl 40','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('525-113','Cost Of Trucking Sc Import - Sea Fcl 45','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-115','Cost Of Trucking Sc Import - Sea Lcl','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-116','Cost Of Trucking Import - Sea Truck','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-118','Cost Of Trucking Import - Sea Gen. Charge','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-201','Cost Of Trucking Sc Export - Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-208','Cost Of Trucking Export - Air Gen. Charge','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-211','Cost Of Trucking Sc Export - Sea Fcl 20','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-212','Cost Of Trucking Sc Export - Sea Fcl 40','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-213','Cost Of Trucking Sc Export - Sea Fcl 45','D','PL',NULL,0,'active',NULL,NULL),
	 ('525-215','Cost Of Trucking Sc Export - Sea Lcl','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('525-218','Cost Of Trucking Export - Sea Gen. Charge','D','PL',NULL,0,'active',NULL,NULL),
	 ('526-000','Cost Of Logistic','D','PL',NULL,0,'active',NULL,NULL),
	 ('526-101','Cost Of Fulfillment','D','PL',NULL,0,'active',NULL,NULL),
	 ('526-102','Cost Of Rental Logistsic','D','PL',NULL,0,'active',NULL,NULL),
	 ('526-103','Cost Of Contract Logistic','D','PL',NULL,0,'active',NULL,NULL),
	 ('526-104','Cost Of Trucking Logistic','D','PL',NULL,0,'active',NULL,NULL),
	 ('527-000','Cost Of Transfer Edi','D','PL',NULL,0,'active',NULL,NULL),
	 ('527-101','Cost Of Transfer Edi Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('527-111','Cost Of Transfer Edi Sea','D','PL',NULL,0,'active',NULL,NULL),
	 ('528-000','Cost Of Insurance','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('528-101','Cost Of Insurance Import Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('528-111','Cost Of Insurance Import Sea','D','PL',NULL,0,'active',NULL,NULL),
	 ('528-201','Cost Of Insurance Export Air','D','PL',NULL,0,'active',NULL,NULL),
	 ('528-211','Cost Of Insurance Export Sea','D','PL',NULL,0,'active',NULL,NULL),
	 ('529-001','Claim Of Goods Damage/Missing','D','PL',NULL,0,'active',NULL,NULL),
	 ('529-002','Third Party Commision','D','PL',NULL,0,'active',NULL,NULL),
	 ('529-003','Operational Retribution','D','PL',NULL,0,'active',NULL,NULL),
	 ('529-005','Storage & Packaging Material','D','PL',NULL,0,'active',NULL,NULL),
	 ('611-001','Promotion Materials','D','PL',NULL,0,'active',NULL,NULL),
	 ('611-002','Advertising Expense','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('611-003','Entertaintment','D','PL',NULL,0,'active',NULL,NULL),
	 ('611-009','Community Services','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-001','Salary & Wages','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-002','Overtime','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-003','Meals & Allowance','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-004','Bpjs Ketenagakerjaan','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-005','Bpjs Kesehatan','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-006','Transport Allowance & Incentive','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-007','Retrenchment','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-008','Bonus & Thr','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('621-009','Pph 21 Allowance','D','PL',NULL,0,'active',NULL,NULL),
	 ('621-010','Refund Third Party','D','PL',NULL,0,'active',NULL,NULL),
	 ('622-001','Electricity','D','PL',NULL,0,'active',NULL,NULL),
	 ('622-002','Telephone','D','PL',NULL,0,'active',NULL,NULL),
	 ('622-003','Internet','D','PL',NULL,0,'active',NULL,NULL),
	 ('622-004','Handphone','D','PL',NULL,0,'active',NULL,NULL),
	 ('622-005','Water Expenses','D','PL',NULL,0,'active',NULL,NULL),
	 ('622-006','Equipment Fuel & Gas','D','PL',NULL,0,'active',NULL,NULL),
	 ('623-001','Vehicle Fuel,Toll & Parking','D','PL',NULL,0,'active',NULL,NULL),
	 ('623-002','Public Transportation','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('624-001','Ticket & Accomodation','D','PL',NULL,0,'active',NULL,NULL),
	 ('624-002','Official Trav - Transport Exp','D','PL',NULL,0,'active',NULL,NULL),
	 ('624-003','Official Trav - Meal Exp','D','PL',NULL,0,'active',NULL,NULL),
	 ('625-002','Building Rep & Maint','D','PL',NULL,0,'active',NULL,NULL),
	 ('625-003','Vehicle Rep & Maint','D','PL',NULL,0,'active',NULL,NULL),
	 ('625-004','Office Equipt Rep & Maint','D','PL',NULL,0,'active',NULL,NULL),
	 ('625-005','Warehouse Equipt Rep & Maint','D','PL',NULL,0,'active',NULL,NULL),
	 ('625-006','Furn & Fixture Rep & Maint','D','PL',NULL,0,'active',NULL,NULL),
	 ('625-008','It Repair And Maintenance','D','PL',NULL,0,'active',NULL,NULL),
	 ('631-001','Printing & Stationery','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('631-002','Stamp Duties','D','PL',NULL,0,'active',NULL,NULL),
	 ('632-001','Postage & Courier','D','PL',NULL,0,'active',NULL,NULL),
	 ('632-002','Household & Pantry','D','PL',NULL,0,'active',NULL,NULL),
	 ('632-003','Routine Retribution','D','PL',NULL,0,'active',NULL,NULL),
	 ('632-004','Donation Expense','D','PL',NULL,0,'active',NULL,NULL),
	 ('632-005','Shortage/Over Of Receive & Payment','D','PL',NULL,0,'active',NULL,NULL),
	 ('633-001','Notary Fee','D','PL',NULL,0,'active',NULL,NULL),
	 ('633-002','Permit & Lisence','D','PL',NULL,0,'active',NULL,NULL),
	 ('633-003','Pajak Bumi & Bangunan','D','PL',NULL,0,'active',NULL,NULL),
	 ('634-001','Professional Fee','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('634-002','Security & Cleaning Service','D','PL',NULL,0,'active',NULL,NULL),
	 ('635-001','Training And Workshop','D','PL',NULL,0,'active',NULL,NULL),
	 ('635-002','Meeting Expense','D','PL',NULL,0,'active',NULL,NULL),
	 ('635-003','Employee Welfare','D','PL',NULL,0,'active',NULL,NULL),
	 ('635-004','Covid 19 Expenses','D','PL',NULL,0,'active',NULL,NULL),
	 ('635-008','Uniform & Safety','D','PL',NULL,0,'active',NULL,NULL),
	 ('636-001','Property Insurance','D','PL',NULL,0,'active',NULL,NULL),
	 ('636-002','Vehicle Insurance','D','PL',NULL,0,'active',NULL,NULL),
	 ('636-003','Medical Insurance','D','PL',NULL,0,'active',NULL,NULL),
	 ('637-001','Office Rental','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('637-002','Warehouse Rental','D','PL',NULL,0,'active',NULL,NULL),
	 ('637-003','Vehicle Rental','D','PL',NULL,0,'active',NULL,NULL),
	 ('650-001','Customer Reimb Expense','D','PL',NULL,0,'active',NULL,NULL),
	 ('651-001','Bank Charges','D','PL',NULL,0,'active',NULL,NULL),
	 ('661-002','Building Depr. Exp','D','PL',NULL,0,'active',NULL,NULL),
	 ('661-003','Vehicle Depr. Exp','D','PL',NULL,0,'active',NULL,NULL),
	 ('661-004','Office Equip Depr Exp','D','PL',NULL,0,'active',NULL,NULL),
	 ('661-005','Warehouse Equipt Depr. Exp','D','PL',NULL,0,'active',NULL,NULL),
	 ('661-006','Furn & Fixture Depr. Exp','D','PL',NULL,0,'active',NULL,NULL),
	 ('661-008','Software Depr. Exp','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('711-001','Current Account Interest Income','C','PL',NULL,0,'active',NULL,NULL),
	 ('712-001','Gain/Loss On Exchange Rate','C','PL',NULL,0,'active',NULL,NULL),
	 ('713-001','Gain/Loss On Sale Of Assets/Investment','C','PL',NULL,0,'active',NULL,NULL),
	 ('714-001','Gain/Loss On Payment Difference','C','PL',NULL,0,'active',NULL,NULL),
	 ('715-001','Other Income','C','PL',NULL,0,'active',NULL,NULL),
	 ('717-001','Financing Interest Expense','D','PL',NULL,0,'active',NULL,NULL),
	 ('717-003','Loan Interest Expense','D','PL',NULL,0,'active',NULL,NULL),
	 ('718-001','Tax Expense','D','PL',NULL,0,'active',NULL,NULL),
	 ('718-002','Tax Penalty','D','PL',NULL,0,'active',NULL,NULL),
	 ('718-008','Tax Amnesty Expense','D','PL',NULL,0,'active',NULL,NULL);
INSERT INTO public.coa (code,"name",normal_balance,report_type,report_operator,coa_group_id,status,created_at,updated_at) VALUES
	 ('719-001','Other Expenses','D','PL',NULL,0,'active',NULL,NULL),
	 ('811-001','Income Summary','C','PL',NULL,0,'active',NULL,NULL),
	 ('812-001','Current Income Tax','D','PL',NULL,0,'active',NULL,NULL),
	 ('301-001','Initial Capital','C','BS','RATE',0,'active','2023-12-15 10:34:15','2023-12-15 10:34:15');
